### ISSUE TITLE
Does not work anymore?

### ISSUE THREAD

**Issue by etiennea** [joshkehn/JSMessageExample#1]
I cannot find window.webkit is undefined :-(

**Comment by joshkehn** [comment]
Just tried it in the simulator. 

![screen shot 2014-11-12 at 2 10 53 pm](https://cloud.githubusercontent.com/assets/272377/5016630/bd306b4a-6a75-11e4-8d4e-a900e15fe2c2.png)

You need to open the web page _inside_ the `WKWebView` (either on device or in the simulator). Running it in a separate browser won't work.

**Comment by etiennea** [comment]
Figured it out, we were re-instantiating the options which removes window.webkit access

**Comment by joshkehn** [comment]
That's interesting, can you explain a bit more how it happened?

**Comment by etiennea** [comment]
I removed

```
WKWebViewConfiguration *configuration = [[WKWebViewConfiguration alloc] init];
WKUserContentController *controller = [[WKUserContentController alloc] init];
```

and used

```
 _webView.config  
```

and window.webkit reapeared

**Comment by joshkehn** [comment]
Ah, so you were re-initializing the configuration on the `_webView` and that caused the handlers to disappear in JavaScript?

**Comment by etiennea** [comment]
Yes exactly
